//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsoApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public System.Guid Id { get; set; }
        public string Descripcion { get; set; }
        public string Activo { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public decimal Precio { get; set; }
        public string Iva { get; set; }
        public decimal Descuento { get; set; }
        public System.DateTime FECHA_MODIFICACION { get; set; }
        public string USUARIO_MODIFICACION { get; set; }
        public System.Guid Grupo { get; set; }
    
        public virtual GRUPO GRUPO1 { get; set; }
    }
}
